# final_puzzle.rb

require './alphabet_place.rb'

# 10x10 だと1秒で終わってくれる
String.grid_size = 10
$grid = <<GRID25.delete("\n")
ZZZZZZZZZZ
ZZZZZZZZZZ
ZZZZZZZZZZ
ZZZZZZZZZZ
ZZZZZZZZZZ
ZZZZZZZZZZ
ZZZZZZZZZZ
ZZZZZZZZZZ
ZZZZZZZZZZ
ZZZZZZZZZZ
GRID25
#$grid = <<GRID25.delete("\n")
#AZZPZZTZZZZZZWFZZZOZCZZZE
#ZZZXFQBZZZASJZZUYZZLTZZZR
#ZJDLUPOCZZKZNZZQHZZZSZZZZ
#ZKZZZZZZZZEZBHZTZGZWMZJZZ
#ZWZZZZFZZUTYPZZVEMZZZZZQI
#ZZZZTZZKVZZZZZZBFOZEZZZXZ
#ZXYVMBSZZZUDZZZZZZZZZZZZZ
#WZZZZFQZXZZZLZZNRZZYZZZZZ
#ZZZSPECZATMKYOZZZZZZJZZVW
#ZIZZAMZZZZZZZZZZCVZZZZEZZ
#DZNAZZZZZSZUZZZZZZPZVIZHG
#ZZZZZLZZZAQPZZVZZZZRZZCZZ
#ZZKZZZGBOZZZZZZZMNHULZZZZ
#FZUZHZZTQYJZZCAIVZZZZDZKB
#ZQZZZZZZHPOZZRZWGTCSZMUNY
#MATZZJPZLZHZZZZZQWZZZNZRZ
#RZZJSZZYZCZQZEZZZUZHZZZZZ
#IFCZZTZEZZZZKMRPZZZZZZZOH
#QZZDZVZINZBZXSOYZAEZZZGZT
#BLEOVZZSZZZZZYUJTZKZZZWPX
#YDFKCWZAZIZZZZZMZZZGNEZUP
#GZZZQZUZZZNZZZZZZLZZZZYZZ
#XMZWZZZFZKZZZZZZZZZZDZZZZ
#ZEZIZZZZRDZHZZZOZZZAGJBZK
#SZPZBZZNZZZGZUZZKCZZZARIZ
#GRID25

$partial_grid = [
                 "ILOVERUBY",
                 "R\nU\nB\nY\nI\nS\nT"
                ]
answer = AlphabetPlace::Solver.new($grid).solve
puts "*** answer ***"
puts answer.to_grid
