# final_puzzle.rb

require './alphabet_place.rb'

$grid = <<GRID25.delete("\n")
AZZPZZTZZZZZZWFZZZOZCZZZE
ZZZXFQBZZZASJZZUYZZLTZZZR
ZJDLUPOCZZKZNZZQHZZZSZZZZ
ZKZZZZZZZZEZBHZTZGZWMZJZZ
ZWZZZZFZZUTYPZZVEMZZZZZQI
ZZZZTZZKVZZZZZZBFOZEZZZXZ
ZXYVMBSZZZUDZZZZZZZZZRZZZ
WZZZZFQZXZZZLZZNRZZYZUZZZ
ZZZSPECZATMKYOZZZZZZJBZVW
ZIZZAMZZZZZZZZZZCVZZZYEZZ
DZNAZZZZZSZUZZZZZZPZVIZHG
ZZZZZLZZZAQPZZVZZZZRZSCZZ
ZZKZZZGBOZZZZZZZMNHULTZZZ
FZUZHZZTQYJZZCAIVZZZZDZKB
ZQZZZZZZHPOZZRZWGTCSZMUNY
MATZZJPZLZHZZZZZQWZZZNZRZ
RZZJSZZYZCZQZEZZZUZHZZZZZ
IFCZZTZEZZZZKMRPZZZZZZZOH
QZZDZVZINZBZXSOYZAEZZZGZT
BLEOVZZSZZZZZYUJTZKZZZWPX
YDFKCWZAZIZZZZZMZZZGNEZUP
GZZZQZUZZZNZZZZZZLZZZZYZZ
XMZWZZZFZKILOVERUBYZDZZZZ
ZEZIZZZZRDZHZZZOZZZAGJBZK
SZPZBZZNZZZGZUZZKCZZZARIZ
GRID25

$partial_grid = [
                 "ILOVERUBY",
                 "R\nU\nB\nY\nI\nS\nT"
                ]
answer = AlphabetPlace::Solver.new($grid).solve
puts "*** answer ***"
puts answer.to_grid
